### ISSUE TITLE
Class Component?

### ISSUE THREAD

**Issue by pegues** [row1/react-declarative-d3#5]
How do you convert this into a class component?

**Comment by row1** [comment]
Hi,

I can give you some tips, but can't help you diagnose this at the moment.

You probably don't need to move all the functions/variables to be inside `MultiSeriesLineChart`.  You can just change things like `svgWidth` and `margin` to be props that get passed in.

You then need to setup things like `x`, `y`, etc once (any only once) when the component mounts using the `useEffect` hook or change it to a class.
